run git commands from www-data

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,7 +32,7 @@ jobs:
             sudo chmod -R 2775 $APP_DIR || { echo "Failed to change permissions"; exit 1; }
             sudo usermod -aG www-data root || { echo "Failed to add user to group"; exit 1; }
             echo "Cloning repository"
-            sudo git clone $REPO_URL $APP_DIR || { echo "Failed to clone repository"; exit 1; }
+            sudo -u www-data git clone $REPO_URL $APP_DIR || { echo "Failed to clone repository"; exit 1; }
           fi
                     
           # Run deploy.sh script after ensurin it is exist and executable
